### ISSUE TITLE
Nuve

### ISSUE THREAD

**Issue by ruzgarhasan** [cbilgili/zemberek-nlp-server#1]
Nuve için de Docker paketi oluşturabilir misiniz acaba ?
https://github.com/hrzafer/nuve

Yada Zemberek içe kelime parçalayıp birleştirme bölümünü nasıl kullanabiliriz ?

**Comment by cbilgili** [comment]
Cümleyi kelimelere ayırmak için /simple_tokenization endointini kullanabilirsiniz. Kelimelerin analizi gerekiyorsa da /analyze_sentence endpoinitini kullanabilirsiniz.

**Comment by ruzgarhasan** [comment]
**analyze_sentence** kullanıyorum bu işimi görüyor. fakat buradan çıkan sonuç aşağıda ben bu aşağıdaki sonucu tekrar toparlayıp **bodrum** a çevirmek istiyorum. Bunu hangi methodla yapabilirim.
**bodrum+Noun+A3sg+Pnon+Nom**

**Comment by cbilgili** [comment]
Bunu tam anlayamadım, tekrar bodrum'a nasıl çevirmek istiyorsunuz?

**Comment by ruzgarhasan** [comment]
Mesela Nüve de  **Morphologic Generation** olayı var.  Kökden kelime üretme. Ben şuanda **analyze_sentence** ile kelimeyi parçalıyorum.  Aşağıdaki şekildeki gibi toparlamak istiyorum.

Örnek vermek gerekirse;

//Method 1: Specify the ids of the morphemes that constitute the word
var word1 = tr.Generate("kitap/ISIM", "IC_COGUL_lAr", "IC_SAHIPLIK_BEN_(U)m",
"IC_HAL_BULUNMA_DA","IC_AITLIK_ki", "IC_COGUL_lAr", "IC_HAL_AYRILMA_DAn");

//Method 2: Specify the string representation of the analysis of the word.
string analysis = "kitap/ISIM IC_COGUL_lAr IC_SAHIPLIK_BEN_(U)m";
var word2 = tr.GetWord(analysis);

Console.WriteLine(word1.GetSurface()); //kitaplarımdakilerden
Console.WriteLine(word2.GetSurface()); //kitaplarım

**Comment by cbilgili** [comment]
Anladım, şu an API üzerinde öyle bir endpoint bulunmuyor.

https://github.com/ahmetaa/zemberek-nlp/tree/master/morphology sayfasında kelime oluşturma özelliği tarif edilmiş. 

Yeni versiyona geçişle birlikte onu da eklemeye çalışacağım. Sayfayı inceleyip aklınıza gelebilecek önemli noktaları yazarsanız (parametreler vb), ona göre ilerleyeyim.

**Comment by ruzgarhasan** [comment]
Süper, şimdiden ellerinize sağlık.
**analyze_sentence** yaptığımızda **[yağmak:Verb] yağ:Verb+acak:Fut+A3sg** sonucunu alıyoruz.
Bu sonucu işlemeden direk **morphology**  ye gönderdiğimizde parçalaması gerekecek.

` morphology.getWordGenerator().generate(item, numberM, possessiveM, caseM);`

Yukarıda parçalı şekilde verdiğimizde getiriyor. Burada parçalama mantığı oluştırmak gerekiyor. 
":" işaretinden ayırıp göndermek gerekli galiba..

**Comment by cbilgili** [comment]
Tamamdır, bu tabi web API olduğu için gerekli alanlar için array göndermek daha ideal olabilir.

**Comment by cbilgili** [comment]
Metin parçalamak için de bir alan olabilir duruma göre

**Comment by cbilgili** [comment]
@ruzgarhasan /generate_words endpointini hazırladım. Parametre olarak word ve morphemes bulunuyor.
Örnek olarak yürümek ve Verb,Fut,Past,A3sg verildiği zaman yürüyecekti sonucunu üretiyor.

Bir kontrol edebilir misiniz?

<img width="1208" alt="ekran resmi 2018-08-16 16 06 43" src="https://user-images.githubusercontent.com/1267433/44210154-66ebbd00-a16e-11e8-964f-f72f7c5d3061.png">

**Comment by ruzgarhasan** [comment]
Kontrol ettim fakat aşağıdaki hatayı alıyorum.  **generate_words** fonksiyonunu bulamıyor. Git güncellemesini yaptım fakat sonuç aynı.
- The requested route [/generate_words] has not been mapped

**Comment by cbilgili** [comment]
Adres değişikliği olmuştu, şu komutlarla tekrar son dockerı çekebilir misiniz?
```
docker pull cbilgili/zemberek-nlp-server:1.1
docker run -p 4567:4567 cbilgili/zemberek-nlp-server:1.1
```

**Comment by cbilgili** [comment]
endpointde /generate_word olarak güncellendi.

**Comment by ruzgarhasan** [comment]
Elinize sağlık baya iyi çalışıyor fakat şuarada bir karışıklık oluyor. Kelimeyi toparlarken parçaladığımız veriyi kullanamıyoruz.
Örneğin;
yürümek kelimesini parçaladığımızda aşağıdaki sonuç çıkıyor toplamak istediğimizde buradaki veriyi kullanmamız lazım **morphemes** bölümüne aşağıdaki sonuctan **oflazer** veya hangisi uygun olursa o bölümü yazarak bu işi yapabiliyor olmamız lazım.
`Array
(
    [root] => yürü
    [dictionary_item_name] => yürümek
    [long_format] => [yürümek:Verb] yürü:Verb|mek:Inf1→Noun+A3sg
    [no_surface] => Verb|Inf1→Noun+A3sg
    [no_empty] => 
    [oflazer] => yürü+Verb^DB+Noun+Inf1+A3sg
    [only_igs] => 
)
`

**Comment by ruzgarhasan** [comment]
find_pos veya  analyze_word fonksiyonları kullanılabilir find_pos daha uygun bu işlem için.
**[morphemesLexical] => Verb|Able→Verb+Aor+A1sg** çıkan sonuçtaki | ve → işaretleri geldiği için sorun oluşturuyor.

**Comment by ruzgarhasan** [comment]
İnceleme şansınız oldu mu acaba ?

**Comment by cbilgili** [comment]
@ruzgarhasan Yurtdışında olduğum için bakma şansım olmadı, en kısa sürede inceleyeceğim.

**Comment by cbilgili** [comment]
@ruzgarhasan Güncellemeyi yayına aldım. no_surface alanındaki değeri yeni kelime oluşturmak için kullanabilirsiniz. Örneğin; Verb|Inf1→Noun+A3sg. Deneyince haber verirseniz sevinirim.

**Comment by ruzgarhasan** [comment]
Elinize sağlık çok başarılı bir iş çıkartmışsınız. 👍
