### ISSUE TITLE
Zemberek 0.15

### ISSUE THREAD

**Issue by mdakin** [cbilgili/zemberek-nlp-server#2]
Ozellikle 0.12 versiyonundan itibaren zemberek'te buyuk guncellemeler yapildi (https://github.com/ahmetaa/zemberek-nlp/blob/master/CHANGELOG.md) bu yuzden en son versiyon olan 0.15 e gecmek anlamli olabilir. (Kullandigin bazi apiler kirilmis olabilir)

**Comment by cbilgili** [comment]
Evet, 0.14'de NER'de ilgi çekici. Ama yeni versiyonlar biraz daha stabilleşene kadar 0.12 yeterli olacak gibi.

**Comment by mdakin** [comment]
Su anda 0.11.1 kullaniliyor gordugum kadariyla,  >= 0.12 olmasi avantaj olabilir cunku morfolojik analiz ve belirsizlik giderici tamamen bastan yazildi, bellek kullanimi ve startup hizinin da daha iyi olmasi gerekir.

**Comment by cbilgili** [comment]
Çok iyi, İnceleyip nasıl bir geçiş yapılabilir bakacağım.

**Comment by mdakin** [comment]
Kendi forkumda yeni versiyona gecis icin degisikliklere basladim, tamamlaninca bir PR gonderirim
https://github.com/mdakin/zemberek-nlp-server/commit/057de27cba58895548f956b8b39bd743d3eb89a7

**Comment by mdakin** [comment]
https://github.com/cbilgili/zemberek-nlp-server/pull/3

**Comment by cbilgili** [comment]
@mdakin Ellerinize sağlık tekrar, pull requesti birleştirdim. Siz de şöyle bir kontrol ederseniz, geçişi tamamlamış olalım.

**Comment by mdakin** [comment]
Baslangic icin tamam gibi. tesekkurler.
