### ISSUE TITLE
Metin Sınıflandırma

### ISSUE THREAD

**Issue by ruzgarhasan** [cbilgili/zemberek-nlp-server#6]
Zemberek teki "**[classification](https://github.com/ahmetaa/zemberek-nlp/wiki/Zemberek-NLP-ile-Metin-S%C4%B1n%C4%B1fland%C4%B1rma)**" kısmını api a nasıl ekleyebiliriz ?

Birde sizi uğraştırmamak için bende destek olmak istiyorum. Bu tarz eklemeleri nasıl yaptığınıza dair bir açıklama veya yaparken videoya alırsanız çok daha yararlı olacaktır.

**Comment by mdakin** [comment]
@ruzgarhasan Merak ettim nerede kullanacaksiniz classification modulunu?

**Comment by ruzgarhasan** [comment]
Sosyal medya hesaplarında post analizi ve kategorilendirmesi yapmak için kullanacağım. @mdakin

**Comment by mdakin** [comment]
@ruzgarhasan akademik bir calisma mi?

**Comment by ruzgarhasan** [comment]
@mdakin Hayır, kişisel bir proje de kendimi ve projeyi geliştirmek için.

**Comment by cbilgili** [comment]
@ruzgarhasan Sınıflandırma konusu docker üzerinde şu anki aşamada çok pratik olmayacak.

Normal şartlarda hyperparametreleri ayarlamak, tekil/çoğul, heceleme gibi ince ayarlar yapılması gerekir. Önerim kendi kullandığınız kütüphanede (örn keras veya tensorflow) zemberekten aldığınız analizleri kullanmanız.
