### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by esersahin** [cbilgili/zemberek-nlp-server#7]
Merhabalar, asagida ki 3. satirin calismasi sirasinda ekran goruntusunu paylastigim hata ile karsilastim.
Islemler Windows 10 Pro isletim sistemi kurulu makine uzerinde gerceklestirilmektedir.

1. git clone https://github.com/cbilgili/zemberek-nlp-server.git
2. cd zemberek-nlp-server
3. mvn clean install

Sorunun neden kaynaklandigi konusunda yardimlarinizi rica ediyorum.

![mvn-build-error](https://user-images.githubusercontent.com/4234798/59694187-e2842380-91f0-11e9-95f6-73d1d1375278.png)

**Comment by cbilgili** [comment]
Merhabalar,

hata zemberek-nlp-server/src/main/java/morphology/GenerateWordsController.java dosyasındaki 28. satırdan kaynaklanıyor.

morphemes = morphemes.replace('→', '+');  Orada unicode → karakter bulunuyor. Javayı çalıştırıken https://stackoverflow.com/a/362006/1201954 adresinde tarif edildiği gibi utf8 desteği ile çalıştırmayı deneyebilir misiniz?

Bunlarla uğraşmamak için docker versiyonunu kullanabilirsiniz.

**Comment by esersahin** [comment]
Docker üzerinden indirip calistirdim. 
Ayrıca pom.xml dosyasında project tag'i içerisine aşağıda ki bölümü eklediğimde derleme işlemi başarıyla gerçekleştirildi.

https://stackoverflow.com/questions/3017695/how-to-configure-encoding-in-maven

![build-utf](https://user-images.githubusercontent.com/4234798/59770277-6e10b980-92b0-11e9-8ca0-a13d074b31d0.png)
	 
Yardımlarınız için teşekkürler.
